name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: where are we
      run: pwd
    - name: list some key files
      run: ls -lrt
    - name: Restore dependencies
      run: dotnet restore ./WebApplication1/
    - name: Build
      run: dotnet build --configuration Release --no-restore ./WebApplication1/
    - name: Test
      run: dotnet test --no-build --verbosity normal
